# Generated by Django 4.2.4 on 2023-08-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_Name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Slot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('CourseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.batch')),
                ('CourseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.course')),
                ('Time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.slot')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='Time_Slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.slot'),
        ),
    ]
